name: CI/CD para AWS S3

on:
  push:
    branches:
      - main

jobs:
  # Integração Contínua (CI)
  
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Lint HTML
      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Verificar HTML
        run: htmlhint "**/*.html" || true  # não falha o pipeline, apenas alerta

      # Lint CSS
      - name: Instalar Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Verificar CSS
        run: stylelint "**/*.css" || true

      # Lint JS
      - name: Instalar ESLint
        run: npm install -g eslint

      - name: Verificar JS
        run: eslint "**/*.js" || true

  # Entrega Contínua (CD)

  cd:
    runs-on: ubuntu-latest
    needs: ci  # Só roda o deploy se o CI passar
    if: github.ref == 'refs/heads/main'  # Apenas na branch principal

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Deploy para S3
        run: |
          aws s3 sync . s3://projeto-devops-pucrs-2025/ \
          --exclude ".git/*" --exclude ".github/*" \
          --delete --exact-timestamps
